name = "makers-page-ssr-gateway"
main = "src/worker.ts"
compatibility_date = "2025-07-19"
account_id = "fcb2001206ae0afed10010755eb5b2e1"

kv_namespaces = [
  { binding = "MAKERS_PAGE_KV", id = "79ecb3f23a404fc5ba9ffcbba37c0772" }
]

r2_buckets = [
  { binding = "MAKERS_PAGE_R2", bucket_name = "makers-page-bucket", preview_bucket_name = "makers-page-bucket" }
]

[env.preview]
name = "makers-page-ssr-gateway-preview"
kv_namespaces = [
  { binding = "MAKERS_PAGE_KV", id = "79ecb3f23a404fc5ba9ffcbba37c0772", preview_id = "79ecb3f23a404fc5ba9ffcbba37c0772" }
]
r2_buckets = [
  { binding = "MAKERS_PAGE_R2", bucket_name = "makers-page-bucket", preview_bucket_name = "makers-page-bucket" }
]
