name = "makers-page-ssr-gateway"
main = "src/worker.ts"
compatibility_date = "2023-07-05"

kv_namespaces = [
  { binding = "MAKERS_PAGE_KV", id = "4d8354cca877431f9e08086354ccb22e" }
]


[env.preview]
name = "makers-page-ssr-gateway-preview"
kv_namespaces = [
  { binding = "MAKERS_PAGE_KV", id = "6ef1beb3d9324722869cc2c58027d46f", preview_id = "6ef1beb3d9324722869cc2c58027d46f" }
]
